###Important Data Structure and Algorithm Code


In [ ]:
edges=[(0,2),(0,3),(0,4),(1,2),(1,7),(2,5),(3,5),(3,7),(4,7),(5,6),(6,7)]
size = 8
import numpy as np
AMat = np.zeros(shape=(size,size))
for (i,j) in edges:
    AMat[i,j] = 1
print(AMat)

[[0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


##Code to sort a list using O($n^2$) (Selection Sort)
we will be using Selection sort Algorithm to sort our Array


In [ ]:
l = [21,12,13,42,11,9,15,81,25,50]


In [ ]:
def selection_sort(l):
  n = len(l)
  for i in range(n):
    cpoint = i
    for j in range(i+1,n):
      if l[cpoint]>l[j]:
        cpoint = j
    (l[i],l[cpoint])  = (l[cpoint],l[i])
  return l
print(selection_sort(l))


[9, 11, 12, 13, 15, 21, 25, 42, 50, 81]


<h1>binary search

In [ ]:
def binary_search(l,a):
  b = selection_sort(l)
  n = len(b)
  m = n//2
  if len(b)<=1:
    if b[0]==a:
      return True
    else:
      return False
  else:
    if b[m]==a:
      return True
    else:
      if a<b[m]:
        return binary_search(b[:m],a)
      else:
         return binary_search(b[m:],a)

print(binary_search(l,25))

True


In [ ]:
def binary_search(l,a):
  b = selection_sort(l)
  start = 0
  end = len(l)-1
  num = 0
  found = 0
  while((l[end]-l[start])>1):
    mid = len(b)//2
    if l[mid]==a:
      found = 1
    if l[mid]>a:
      end = mid-1
    if l[mid]<a:
      start = mid+1
    if  l[start]==a or l[end]==a:
      found = 1
    else:
      found = 0
  return found



print(binary_search(l,25))

##Binary Search (via iteration method) O($n^2$)


In [ ]:
def binary_search(L,a):
  L.sort()
  n = len(L)
  start = 0
  end = len(L)-1
  while (end-start)>1:
    mid = (end - start)//2
    if L[mid]==a:
      return True
    if L[mid]>a:
      end = mid-1
    if L[mid]<a:
      start = mid+1
  if L[start]==a or L[end]==a:
    return True
  else:
    return False
print(binary_search(l,5))

False


##Binary Search (via recurssion method) O($n^2$)
method 2

In [ ]:
def binary_search(l,x):
  l.sort()
  mid  = len(l)//2
  begin =0
  end = -1
  if len(l)<=1:
    if l[0]==x:
      return True
    else:
      return False
  else:
    if l[mid]==x:
      return True
    else:
      if x<l[mid]:
        end = mid
        return binary_search(l[begin:end],x)
      else:
        begin = mid+1
        return binary_search(l[begin:],x)

###Binary Search Using Recurssion  O($n^2$)


In [ ]:
def binary2(l,a):
  l.sort()
  end = len(l)-1
  start = 0
  mid = end+start//2
  if end>=start:
    if l[mid]==a:
      return True
    if l[mid]>a:
      end = mid
      return binary2(l[:end],a)
    if l[mid]<a:
      start = mid+1
      return binary2(l[start:],a)
  else:
    return False
print(binary2(l,81))

True


###Selection sort  O($n^2$)

In [ ]:
def selection_sort(l):
  n = len(l)
  if len(l)<=1:
    return l
  for i in range(n):
    cpoint = i
    for j in range(i+1,n):
      if l[cpoint]> l[j]:
        cpoint = j
    (l[i],l[cpoint])=(l[cpoint],l[i])
  return l

print(selection_sort(l))


[9, 11, 12, 13, 15, 21, 25, 42, 50, 81]


###Insertion sort  O($n^2$)

In [ ]:
def insertion_sort(l):
  n = len(l)
  for i in range(n):
    j = i
    while j>0 and l[j]<l[j-1]:
      (l[j],l[j-1])=(l[j-1],l[j])
      j = j-1
  return l
print(insertion_sort(l))

[9, 11, 12, 13, 15, 21, 25, 42, 50, 81]


<h1> Merge Sort O(nlogn) </h1>

run the merge code first then run the merge sort block



In [ ]:
def merge_sort(l):
  n = len(l)
  if n<=1:
    return l
  L = merge_sort(l[:n//2])
  R = merge_sort(l[n//2:])
  b = merge(L,R)
  return b

print(merge_sort(l))

[9, 11, 12, 13, 15, 21, 25, 42, 50, 81]


<h1> Merge Algorithm</h1>
<h3>Run this algorithm first, then execute Merge sort Algorithm</h3>

In [ ]:
def merge(a,b):
  (n,m) = (len(a),len(b))
  (c,j,k,i) = ([],0,0,0)
  while k<m+n:
  # here we will check if i=0 is equal to n, because if it is, then the list A, is empty and B still as emlemets,
  # so we will copy remaning elements in c
    if i == n:
      c.extend(b[j:])
    # here j = number of times b was added in the list c, and m contains the total length
    # therefore   m-j will give the number of elements left in b
      k = k+(m-j)
    # nxt we do same with list a
    elif j==m:
      c.extend(a[i:])
      k = k+(n-i)
    elif a[i]<b[j]:
      c.append(a[i])
      k = k+1
      i = i+1
    else:
      c.append(b[j])
      k = k+1
      j=j+1
  return c

<h1> Quick Sort, O(nlogn) in most of the cases and, in Rare Case it may take  O($n^2$)</h1>

In [ ]:
# L = list, l= pivort , r = len(L)
def quicksort(L,l,r):  # Sort L[l:r]
  if (r - l < 1):
    return (L)
  (pivot,lower,upper) = (L[1],l+1,l+1)
  for i in range(l+1,r):
    if L[i] > pivot:  # Extend upper segment
      upper = upper+1
    else:  # Exchange L[i] with start of upper segment
      (L[i], L[lower]) = (L[lower], L[i])
      # Shift both segments
      (lower,upper) = (lower+1,upper+1)
  # Move pivot between lower and upper
  (L[l],L[lower-1]) = (L[lower-1],L[l])
  lower = lower-1
  # Recursive calls
  quicksort(L,l,lower)
  quicksort(L,lower+1,upper)
  return(L)
print(quicksort(l,5,len(l)))

[21, 12, 13, 42, 11, 9, 15, 81, 25, 50]


<h1> Quick Sort

In [ ]:
#lower = 0 or any index required to statrt the loop, upper = len(list)
def partition(L,lower,upper):
  # we are selecting first element as a pivot
  pivot = L[lower]
  i = lower
  for j in range(lower+1,upper+1):
    if L[j] <= pivot:
      i += 1
      L[i],L[j] = L[j],L[i]
  L[lower],L[i]= L[i],L[lower]
  #returning the position of pivot
  return i

def quicksort(L,lower,upper):
  if(lower < upper):
    pivot_pos = partition(L,lower,upper);
    # calling the quick sort on leftside part of pivot
    quicksort(L,lower,pivot_pos-1)
    # calling the quick sort on rightside part of pivot
    quicksort(L,pivot_pos+1,upper)
  return L

print(quicksort(l,0,len(l)-1))

[9, 11, 12, 13, 15, 21, 25, 42, 50, 81]


<h1>Nodes in Python --1

create a Node class

In [ ]:
class Node:
  def __init__(self,v= None):
    self.v = v
    self.next = None
    return
  def isempty(self):
    if self.v ==None:
      return True
    else:
      return False


In [ ]:
#check if node class is working or not

l1 = Node()
l2 = Node(5)
l1.isempty(),l2.isempty()

(True, False)

<h1> Nodes in Python--2

append in the nodes

In [ ]:
class Node:
  def __init__(self,v= None):
    self.v = v
    self.next = None
    return
  def isempty(self):
    if self.v ==None:
      return True
    else:
      return False
  #THIS IS APPEND
  # GAP LEFT FOR THE CODE TO BE MORE VISIBLE
  #-------
  #----
  def append(self,v):
    if self.isempty():
      self.v = v
    elif self.next==None:
      self.next = Node(v)
    else:
      self.next.append(v)
  #--------------APPEND----CODE---END--------------#

In [ ]:
class queue:
    def __init__(self):
        self.v = []

    def addq(self, s):
        self.v.append(s)

    def isempty(self):
        if self.v == []:
            return True
        else:
            return False

    def delq(self):
        vi = None
        if self.isempty() == False:
            vi = self.v[0]
            self.v = self.v[1:]
        return vi
    def __str__(self):
        return (str(self.v))


def bfs(alist, p):
    visited = {}
    for i in alist.keys():
        visited[i] = False
    q = queue()
    visited[p] = True
    q.addq(p)

    while q.isempty() == False:
        j = q.delq()
        for k in alist[j]:
            visited[k] = True
            q.addq(k)
    return visited

def components(alist):
    component = {}
    for i in alist.keys():
        component[i]=-1
    (compid,seen)  =  (0,0)
    while seen<=(max(alist.keys())):
        startid = min([i for i in alist.keys() if component[i]==-1])
        visited = bfs(alist,startid)
        for i in visited.keys():
            if visited[i] == True:
                seen = seen+1
                component[i] = compid
        compid = compid + 1
    return component


AList = {0: [1], 1: [2], 2: [0], 3: [4, 6], 4: [3, 7], 5: [3, 7], 6: [5], 7: [4, 8], 8: [5, 9], 9: [8]}
print(components(AList))

KeyboardInterrupt: ignored

In [ ]:
class Queue:
    def __init__(self):
        self.queue = []
    def addq(self,v):
        self.queue.append(v)
    def isempty(self):
        return(self.queue == [])
    def delq(self):
        v = None
        if not self.isempty():
            v = self.queue[0]
            self.queue = self.queue[1:]
        return(v)
    def __str__(self):
        return(str(self.queue))

def BFSList(AList,v):
    visited = {}
    for i in AList.keys():
        visited[i] = False
    q = Queue()

    visited[v] = True
    q.addq(v)

    while(not q.isempty()):
        j = q.delq()
        for k in AList[j]:
            if (not visited[k]):
                visited[k] = True
                q.addq(k)
    return(visited)
def Components(AList):
    component = {}
    for i in AList.keys():
        component[i] = -1
    (compid,seen) = (0,0)
    while seen <= max(AList.keys()):
        startv = min([i for i in AList.keys() if component[i] == -1])
        visited = BFSList(AList,startv)
        for i in visited.keys():
            if visited[i]:
                seen = seen + 1
                component[i] = compid
        compid = compid + 1
    return(component)
AList = {0: [1], 1: [2], 2: [0], 3: [4, 6], 4: [3, 7], 5: [3, 7], 6: [5], 7: [4, 8], 8: [5, 9], 9: [8]}
print(Components(AList))

{0: 0, 1: 0, 2: 0, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}


In [ ]:
dedges = [(0,1,10),(0,2,80),(1,2,6),(1,4,20),(2,3,70),(4,5,50),(4,6,5),(5,6,10)]
size = 7
import numpy as np
W = np.zeros(shape=(size,size,2))
for (i,j,w) in dedges:
    W[i,j,0] = 1
    W[i,j,1] = w
print(W)



[[[ 0.  0.]
  [ 1. 10.]
  [ 1. 80.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 1.  6.]
  [ 0.  0.]
  [ 1. 20.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 70.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 50.]
  [ 1.  5.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. 10.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


In [ ]:
w = np.zeros(shape=(3,3,3))
print(w)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
list1 = [[[1,2],[3,4],[5,6]],[[7,8],[9,10]]]
n= len(list1)
for i in list1:
  n = len(i)
  for j in range(n):
    print(i[j][1])


2
4
6
8
10
